# These are implementations to be run both at the server and client
implementations: [quiche]
# The number of times the run must be made
measurement_metrics: [goodput]
repetitions: 2
# The file size in MB to transfer between the two hosts. 
filesize: 1024
# The following entries describe the script to run at the host.
client_prerunscript: []
server_prerunscript: []
client_postrunscript: []
server_postrunscript: []
build_script: 'build_optimised.sh' # can be also build.sh for debug