# These are implementations to be run both at the server and client
implementations: [mpquic, mcmpquic]
measurement_metrics: [goodput]
# The number of times the run must be made
repetitions: 10
# The file size in MB to transfer between the two hosts. 
filesize: 4096
# The number of concurrent clients to run
concurrent_clients: 1
# The following entries describe the script to run at the host.
client_prerunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/start-cpu-monitor.sh
    blocking: true
  - path: pre-post-scripts/run-bandwidth-monitor.sh
    blocking: true

client_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-cpu-monitor.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh

server_prerunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/start-cpu-monitor.sh
    blocking: true
  - path: pre-post-scripts/run-bandwidth-monitor.sh
    blocking: true

server_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-cpu-monitor.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh

client_implementaion_params:
  rmem_value: 100000000 # 100MB
server_implementaion_params:
  rmem_value: 100000000 # 100MB

build_script: 'build_optimised.sh' # can also be build.sh for debug