implementations: [mpquic, mcmpquic]
measurement_metrics: [throughput]
repetitions: 10
duration: 120 # seconds
concurrent_clients: 1
client_prerunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/start-cpu-monitor.sh
    blocking: true
  - path: pre-post-scripts/run-bandwidth-monitor.sh
    blocking: true

client_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-cpu-monitor.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh

server_prerunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/start-cpu-monitor.sh
    blocking: true
  - path: pre-post-scripts/run-bandwidth-monitor.sh
    blocking: true

server_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-cpu-monitor.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh

client_implementaion_params:
  rmem_value: 100000000 # 100MB
server_implementaion_params:
  rmem_value: 100000000 # 100MB

build_script: 'build_optimised.sh' # can also be build.sh for debug