implementations: [mpquic, mcmpquic]
measurement_metrics: [throughput]
repetitions: 2
duration: 10 # seconds
concurrent_clients: 1
nb_paths: [1, 4, 8, 12, 16]
client_prerunscript:
  - path: pre-post-scripts/off-ht.sh
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/run-strace.sh
    blocking: true
  - path: pre-post-scripts/run-bandwidth-monitor.sh # needed
    blocking: true
    
client_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-strace.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh
  
server_prerunscript:
  - path: pre-post-scripts/off-ht.sh
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/run-bandwidth-monitor.sh # needed
    blocking: true
    
server_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh
  
client_implementation_params:
  rmem_value: 100000000 # 100MB
  app_cpu_aff: "0-16"

server_implementation_params:
  rmem_value: 100000000 # 100MB
  app_cpu_aff: "0-16"

build_script: 'build_optimised.sh'