implementations: [mcmpquic]
measurement_metrics: [throughput]
repetitions: 2 # 10
duration: 20 # seconds
concurrent_clients: 1
nb_paths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
client_prerunscript:
  - path: pre-post-scripts/on-ht.sh
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/run-rx-interrupts.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/start-cpu-monitor.sh
    blocking: true
  - path: pre-post-scripts/run-bandwidth-monitor.sh
    blocking: true

client_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/run-rx-interrupts.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-cpu-monitor.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh

server_prerunscript:
  - path: pre-post-scripts/on-ht.sh
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/run-rx-interrupts.sh
  - path: pre-post-scripts/set-rcvbuf.sh
  - path: pre-post-scripts/start-cpu-monitor.sh
    blocking: true
  - path: pre-post-scripts/run-bandwidth-monitor.sh
    blocking: true

server_postrunscript:
  - path: pre-post-scripts/run-ethtool.sh
  - path: pre-post-scripts/run-netstat.sh
  - path: pre-post-scripts/run-rx-interrupts.sh
  - path: pre-post-scripts/set-buffers-default.sh
  - path: pre-post-scripts/stop-cpu-monitor.sh
  - path: pre-post-scripts/stop-bandwidth-monitor.sh

client_implementation_params:
  rmem_value: 100000000 # 100MB
  app_cpu_aff: "0-16"
server_implementation_params:
  rmem_value: 100000000 # 100MB
  app_cpu_aff: "0-16"

build_script: 'build_optimised.sh' # can also be build.sh for debug